name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Prepare SSH key
      run: |
        # ~/.ssh ディレクトリを作成
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa_ec2
        chmod 600 ~/.ssh/id_rsa_ec2
        ls -l ~/.ssh/id_rsa_ec2

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_ec2 ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          set -e  # エラーが出たら即終了
          sudo dnf install -y git  # Git がない場合はインストール
          if [ ! -d "/home/ec2-user/my_project" ]; then
            echo "ディレクトリが存在しません: /home/ec2-user/my_project"
            exit 1
          fi
          cd /home/ec2-user/my_project
          git pull
        EOF
